pkgs/intl/lib/src/intl/date_format.dart, pkgs/intl/test/date_time_loose_parsing_test.dart, pkgs/intl/test/date_time_strict_test.dart
- tryParse
- tryParseStrict
- tryParseLoose
- tryParseUtc
- add tests
related issue https://github.com/dart-lang/i18n/issues/191
original pr https://github.com/dart-lang/intl/pull/578
=> add tryParse methods to DateFormat

pkgs/intl/CHANGELOG.md, pkgs/intl/pubspec.yaml
Apparently there was some error introduced by the migration to a monorepo, leading to copybara overwriting some changes. This reverts them.
=> Fix mistaken copybara imports

pkgs/intl/lib/find_locale.dart, pkgs/intl/lib/intl_default.dart
Fix the missing stub for the conditional export in `find_locale.dart`.
---
Many Dart repos have a weekly cadence for reviewing PRs - …
=> Add stub for conditional export

.github/workflows/health.yaml, pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/README.md, pkgs/intl4x/lib/intl4x.dart, pkgs/intl4x/lib/list_format.dart, pkgs/intl4x/lib/src/list_format/list_format.dart, pkgs/intl4x/lib/src/list_format/list_format_4x.dart, pkgs/intl4x/lib/src/list_format/list_format_ecma.dart, pkgs/intl4x/lib/src/list_format/list_format_impl.dart, pkgs/intl4x/lib/src/list_format/list_format_options.dart, pkgs/intl4x/lib/src/list_format/list_format_stub.dart, pkgs/intl4x/pubspec.yaml, pkgs/intl4x/test/ecma/list_format_test.dart, pkgs/intl4x/test/icu4x/list_format_test.dart
Add list formatting from ECMA402.
Regarding the failing health workflow: I am deferring to adding the missing license header as a test of https://github.com/dart-lang/ecosystem/pull/134; when this is merged I will add and see if the check then passes.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
=> Add intl4x list format

pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/lib/display_names.dart, pkgs/intl4x/lib/intl4x.dart, pkgs/intl4x/lib/src/display_names/display_names.dart, pkgs/intl4x/lib/src/display_names/display_names_4x.dart, pkgs/intl4x/lib/src/display_names/display_names_ecma.dart, pkgs/intl4x/lib/src/display_names/display_names_impl.dart, pkgs/intl4x/lib/src/display_names/display_names_options.dart, pkgs/intl4x/lib/src/display_names/display_names_stub.dart, pkgs/intl4x/pubspec.yaml, pkgs/intl4x/test/ecma/display_names_test.dart
Add the browser's display names feature.
---
<details>
Note that many Dart repos have a …
=> Add ECMA402 display names

.github/workflows/health.yaml, .github/workflows/publish.yaml
- Switch to a stable `health` workflow version while debugging `package:firehose`.
- Allow numbers in package names, to enable autopublishing of `package:intl4x`.
---
<details>
- Changes to packages require …
=> Workflow changes

.github/workflows/health.yaml, .github/workflows/publish.yaml, pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/README.md, pkgs/intl4x/lib/collation.dart, pkgs/intl4x/lib/datetime_format.dart, pkgs/intl4x/lib/intl4x.dart, pkgs/intl4x/lib/list_format.dart, pkgs/intl4x/lib/number_format.dart, pkgs/intl4x/lib/src/datetime_format/datetime_format.dart, pkgs/intl4x/lib/src/datetime_format/datetime_format_4x.dart, pkgs/intl4x/lib/src/datetime_format/datetime_format_ecma.dart, pkgs/intl4x/lib/src/datetime_format/datetime_format_impl.dart, pkgs/intl4x/lib/src/datetime_format/datetime_format_options.dart, pkgs/intl4x/lib/src/datetime_format/datetime_format_stub.dart, pkgs/intl4x/lib/src/display_names/display_names_4x.dart, pkgs/intl4x/lib/src/display_names/display_names_options.dart, pkgs/intl4x/lib/src/list_format/list_format.dart, pkgs/intl4x/lib/src/list_format/list_format_options.dart, pkgs/intl4x/lib/src/number_format/number_format_options.dart, pkgs/intl4x/lib/src/options.dart, pkgs/intl4x/pubspec.yaml, pkgs/intl4x/test/ecma/datetime_format_test.dart
Add the browsers `DateTime` formatting functionality.
Note: Also has the changes from #683 to run the checks.
---
<details> …
=> Add ECMA402 datetime format to package:intl4x

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/intl.dart, pkgs/intl/lib/src/intl/number_format.dart, pkgs/intl/lib/src/intl/number_parser.dart, pkgs/intl/lib/src/intl/number_parser_base.dart
This is a step towards allowing all of the incredible number formatting work that has been done in this package to be reused for more general or custom purposes. For example, [this feature request](https://github.com/a14n/dart-decimal/issues/52) could then be fairly trivial to implement. 
Sample use case: https://github.com/anqit/dart-decimal-number-parser, happy to hear better ideas to accomplish something similar.
---
<details>
- Contributions to our repos should follow the [Dart style …
=> abstract number parsing

.github/workflows/conformance.yml
Fix errors found on `main` branch.
---
<details>
Note that many Dart repos have a …
=> Fix conformance testing

.github/workflows/conformance.yml, pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/README.md, pkgs/intl4x/lib/intl4x.dart, pkgs/intl4x/lib/plural_rules.dart, pkgs/intl4x/lib/src/plural_rules/plural_rules.dart, pkgs/intl4x/lib/src/plural_rules/plural_rules_4x.dart, pkgs/intl4x/lib/src/plural_rules/plural_rules_ecma.dart, pkgs/intl4x/lib/src/plural_rules/plural_rules_impl.dart, pkgs/intl4x/lib/src/plural_rules/plural_rules_options.dart, pkgs/intl4x/lib/src/plural_rules/plural_rules_stub.dart, pkgs/intl4x/pubspec.yaml, pkgs/intl4x/test/ecma/plural_rules_test.dart, pkgs/intl4x/test/tools/conformance_config.json
Add support for [Plural Rules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules).
---
<details> …
=> Add ECMA `PluralRules` to `package:intl4x`

pkgs/intl_translation/CHANGELOG.md, pkgs/intl_translation/lib/src/messages/message.dart, pkgs/intl_translation/pubspec.yaml
Fixes internal b/281585245, which happens when debugging messages.
---
<details>
Note …
=> Fix error on `toString` of `Message`s.

pkgs/intl_translation/CHANGELOG.md, pkgs/intl_translation/lib/src/messages/submessages/select.dart, pkgs/intl_translation/pubspec.yaml
To avoid a repeat of internal b/320626018, where the name of the arg is not in the list of arguments, for example:
```dart
String messageName(int selectedSurfaces) {
final selectedSurfacesKey = switch (selectedSurfaces) {
0 => 'zero',
1 => 'one',
2 => 'two',
_ => '',
};
return Intl.select(
selectedSurfacesKey,
{
'zero': 'Show zero',
'one': 'Show one',
'two': 'Show two',
'other': 'someteststring'
},
name: 'messageName',
args: [
selectedSurfaces,
],
examples: const {'selectedSurfaces': 1},
desc: 'Label for dropdown selection of surfaces');
}
```
Here, `selectedSurfacesKey` is not in `[selectedSurfaces]`.
---
<details> …
=> Throw if the select arg is not in the list of args

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/message_lookup_by_library.dart, pkgs/intl/test/message_lookup_by_library.dart
Inside of the composite message lookup there is a clause which will never be executed that clears the cache after successfully resolving the locale.
The clause is meant to handle the case where a message is looked up before the messages have been successfully loaded as it leave the cache in a state where `_lastLocale` has been set and `_lastLookup` is null.
Since this clause is broken then any subsequent attempt to access a message from that locale will fail as the `_lookupMessageCatalog` is never called again to load the messages.
---
- [/] I’ve reviewed the contributor guide and applied the relevant portions to this PR.
=> Fix clearing cache of failed locale lookup after successfully resolving locale

pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/pubspec.yaml
As the previous run doesn't want to incorporate the newest changes to `publish.yaml`.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.m …
=> Retrigger publishing of `package:intl4x`

.github/workflows/intl.yml, pkgs/intl/CHANGELOG.md, pkgs/intl/lib/find_locale.dart, pkgs/intl/lib/intl_browser.dart, pkgs/intl/lib/src/http_request_data_reader.dart, pkgs/intl/lib/src/locale/locale_extensions.dart, pkgs/intl/lib/src/locale/locale_implementation.dart, pkgs/intl/pubspec.yaml, pkgs/intl/test/number_format_compact_web_test.dart
Adds support for compiling to WASM engine.
Fixes #801 
---
<details>
Note that many …
=> Support WASM for `package:intl`

.github/workflows/intl.yml, pkgs/intl/CHANGELOG.md, pkgs/intl/lib/find_locale.dart, pkgs/intl/lib/intl_browser.dart, pkgs/intl/lib/src/http_request_data_reader.dart, pkgs/intl/lib/src/locale/locale_extensions.dart, pkgs/intl/lib/src/locale/locale_implementation.dart, pkgs/intl/pubspec.yaml, pkgs/intl/test/number_format_compact_web_test.dart
Reverts dart-lang/i18n#802, as this was merged here and not by copybara, causing breakages in g3.
=> Revert "Support WASM for `package:intl`"

pkgs/intl_translation/CHANGELOG.md, pkgs/intl_translation/pubspec.yaml
Topics help users on pub.dev discover packages and related packages.
You can see a list of [topics here](https://pub.dev/topics).
You can also make your own topics.
Topics are added to pubspec.yaml as follows:
```topics:
- my-topic
- some-other-topic
```
See also: https://dart.dev/tools/pub/pubspec#topics
=> Add `topics` to package intl_translation `pubspec.yaml`

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/src/intl/bidi.dart, pkgs/intl/test/bidi_utils_test.dart
i have noticed the issue numbered #827 and modified the regex in the isRtl in bidi to handle central Kordi .
it should work now , I hope it is an ideal solution
=> added central kordi to the rtl language regex

.github/workflows/conformance.yml, .github/workflows/intl4x.yml, .github/workflows/publish.yaml, pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/pubspec.yaml
This is the minimum SDK version for build hooks to be allowed now apparently.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUT …
=> Update SDK constraint for `pub publish`

pkgs/intl_translation/CHANGELOG.md, pkgs/intl_translation/bin/make_examples_const.dart, pkgs/intl_translation/bin/rewrite_intl_messages.dart, pkgs/intl_translation/lib/src/language_version.dart, pkgs/intl_translation/pubspec.yaml
We're in [the process of](https://github.com/dart-lang/dart_style/issues/1403) moving dart_style to [a new formatting style](https://github.com/dart-lang/dart_style/issues/1253). That involves making the formatter [aware of the language version of what it's formatting](https://github.com/dart-lang/dart_style/issues/1402).
That in turn means that the library API now lets you pass in a language version. In dart_style 2.3.7 [you can pass in a language version but the parameter is optional](https://pub.dev/documentation/dart_style/latest/dart_style/DartFormatter/DartFormatter.html). In the forthcoming 3.0.0 release, that parameter will become mandatory.
This updates the two calls to `DartFormatter()` in intl_translation/bin to pass in a language version. It attempts to look for a surrounding …
=> Pass a language version to DartFormatter().

pkgs/intl_translation/CHANGELOG.md, pkgs/intl_translation/pubspec.yaml
In preparation for the `intl` v0.20.0 release.
---
<details>
Note that …
=> Publish v0.20.1 of intl_translation

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/intl.dart, pkgs/intl/pubspec.yaml
Fixes #916 
---
<details>
Note that many Dart repos have a weekly cadence …
=> Update web dependency constraint to `"^1.1.0"`

pkgs/intl/CHANGELOG.md, pkgs/intl/pubspec.yaml
- rev package:intl to 0.20.1 in prep for publishing
This will let people resolve package:intl `0.20.x` w/ package:web `1.0`.
---
<details> …
=> rev package:intl to 0.20.1 in prep for publishing

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/date_symbol_data_http_request.dart, pkgs/intl/lib/src/http_request_data_reader.dart, pkgs/intl/pubspec.yaml
- remove package:http from package:intl
- run `dart pub run downgrade --tighten`
This uses `fetch` from package:web directly instead of using package:http. This works in this case - the library in question (lib/src/http_request_data_reader.dart) is only ever called from the browser.
This PR moves the package to a `-wip` version; we'll likely want to follow this up with a PR looking to in-line uses of package:web (assuming that that's a tractable amount of code).
---
<details>
- Contributions to our repos should follow the [Dart …
=> remove package:http from package:intl

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/date_symbol_data_http_request.dart, pkgs/intl/lib/intl_browser.dart, pkgs/intl/lib/intl_standalone.dart, pkgs/intl/lib/message_format.dart, pkgs/intl/lib/src/file_data_reader.dart, pkgs/intl/lib/src/http_request_data_reader.dart, pkgs/intl/lib/src/intl/number_format_parser.dart, pkgs/intl/lib/src/lazy_locale_data.dart, pkgs/intl/lib/src/web.dart, pkgs/intl/pubspec.yaml
- remove the dependency on package:web
This removes the dep on package:web by in-lining the pieces we use. This is built on top of https://github.com/dart-lang/i18n/pull/928 - I'd review and land that first; I can update this after.
And - while this analyzes correctly and the tests run - I have not tried running this in a browser. We'd probably want to do that before a publish.
---
<details>
- …
=> remove the dependency on package:web

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/src/intl/constants.dart, pkgs/intl/pubspec.yaml
This PR updates the Turkish Lira (TRY) currency symbol in the simpleCurrencySymbols map from "TL" to "₺" (Unicode: U+20BA). This change aligns with the official symbol for Turkish Lira introduced in 2012.
No functional changes are introduced, as this update only modifies the symbol representation. The change ensures consistency and accuracy in displaying the currency.
Why
The current symbol "TL" is outdated. The Unicode character "₺" is the official and globally recognized symbol for Turkish Lira.
Relevant Issues
N/A – This is a minor update to align with modern standards.
Checklist
I’ve reviewed the contributor guide and applied the relevant portions to this PR.
I’ve verified that the change works as expected and doesn’t introduce any regressions.
No additional tests were added since …
=> Update Turkish Lira (TRY) symbol to ₺ (U+20BA)

pkgs/intl/CHANGELOG.md, pkgs/intl/lib/intl.dart, pkgs/intl/lib/src/intl_helpers.dart, pkgs/intl/test/intl_test.dart, pkgs/intl/test/number_format_test_core.dart
Locale strings with a script such as `zh-Hans-CN` are incorrectly canonicalized as `zh` instead of `zh-CN`. Update the `canonicalizedLocale` function to look for a script subtag and ignore it if found.
Closes: https://github.com/dart-lang/i18n/issues/945
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …
=> feat(intl): ignore script subtags when canonicalizing locale strings

pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/lib/src/hook_helpers/build_options.dart, pkgs/intl4x/lib/src/number_format/number_format_options.dart, pkgs/intl4x/pubspec.yaml
Small bug regarding fraction digits parsing and allow no `hook` options key in the pubspec.
---
<details> …
=> Small fixes to intl4x

.github/workflows/intl4x_artifacts.yml, pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/hook/README.md, pkgs/intl4x/pubspec.yaml, pkgs/intl4x/tool/build_libs.g.dart, tools/regenerate_bindings.sh
- Use a local copy of the `build_libs.dart` script with some fixes
- Remove `(ios, arm)` target, as this is not supported in Flutter
---
<details> …
=> Fix artifact building workflows

pkgs/intl_translation/CHANGELOG.md, pkgs/intl_translation/lib/src/messages/constant_evaluator.dart, pkgs/intl_translation/lib/src/messages/main_message.dart, pkgs/intl_translation/lib/src/messages/message.dart, pkgs/intl_translation/lib/visitors/message_finding_visitor.dart, pkgs/intl_translation/pubspec.yaml, pkgs/intl_translation/test/constant_evaluator_test.dart, pkgs/intl_translation/test/generate_localized/code_map_messages_all.dart, pkgs/intl_translation/test/generate_localized/code_map_messages_all_locales.dart, pkgs/intl_translation/test/generate_localized/code_map_messages_fr.dart, pkgs/intl_translation/test/two_components/app_messages_all.dart, pkgs/intl_translation/test/two_components/app_messages_all_locales.dart, pkgs/intl_translation/test/two_components/app_messages_fr.dart, pkgs/intl_translation/test/two_components/component_messages_all.dart, pkgs/intl_translation/test/two_components/component_messages_all_locales.dart, pkgs/intl_translation/test/two_components/component_messages_fr_xyz123.dart
Allows analyzer version ^7.0.0 and update dart_style to ^3.0.0.
The update of `dart_style` to `^3.0.0` is a breaking change.
Related issue: #950 
---
<details>
- Changes to packages require …
=> feat!: allow analyzer 7.0.0 and update dart_style to ^3.0.0

.github/workflows/intl4x.yml, pkgs/intl4x/CHANGELOG.md, pkgs/intl4x/example_native/pubspec.yaml, pkgs/intl4x/hook/build.dart, pkgs/intl4x/lib/src/hook_helpers/hashes.dart, pkgs/intl4x/lib/src/hook_helpers/version.dart, pkgs/intl4x/pubspec.yaml, pkgs/intl4x/tool/regenerate_hashes.dart, pkgs/intl4x/tool/write_option_file.dart
Switch to new artifacts from ICU4X v2.0. Should have probably shipped with `0.12.0`, but here we are.
---
<details> …
=> Use new artifacts in `package:intl4x`

pkgs/intl/pubspec.yaml
To be merged after https://github.com/flutter/flutter/pull/169286
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testi …
=> Add comment to package:intl pubspec.
