.github/labeler.yml
.github/workflows/intl.yml
.github/workflows/intl_translation.yml
.github/workflows/publish.yaml
README.md

update various repo meta files:
- update the table in the readme to use pub.dev markdown badges and to take the package descriptions from the pubspec files (ed: we may want to update the descriptions in the pubspecs)
- add workflow files for the two packages
- contribute a PR labeling config
- contribute a publishing automation file (we'd need some slight modifications to how the packages are configured at pub.dev)

update various repo meta files

---

pkgs/intl/CHANGELOG.md
pkgs/intl/pubspec.yaml
pkgs/intl_translation/CHANGELOG.md
pkgs/intl_translation/pubspec.yaml

Update the pubspec files to reflect the move to this repo, once merged use autopublish to push this to pub.dev.

Update pubspecs to point to new repository

---

pkgs/intl/CHANGELOG.md
pkgs/intl/lib/src/intl/number_format.dart
pkgs/intl/pubspec.yaml
pkgs/intl/test/number_format_test_core.dart

- add tryParse (wrap Parse)
- add tests
related issue https://github.com/dart-lang/i18n/issues/191
origin pr https://github.com/dart-lang/intl/pull/577

add NumberFormat tryParse and test

---

.github/workflows/pull_request_label.yml

- commit a PR labeller workflow

commit a PR labeller workflow

---

pkgs/intl/CHANGELOG.md
pkgs/intl/lib/src/intl/constants.dart

Fixes #669 as per https://st.unicode.org/cldr-apps/v#/en/C_WAsia/74cf939e369d0a03.
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#T …

Switch currency for QAR from Rial to Riyal as per CLDR data

---

.github/workflows/health.yaml
pkgs/intl/CHANGELOG.md
pkgs/intl/lib/find_locale.dart
pkgs/intl/lib/locale.dart
pkgs/intl/lib/src/global_state.dart
pkgs/intl/test/number_format_compact_icu_test.dart
pkgs/intl/test/number_format_compact_web_test.dart
pkgs/intl_translation/test/message_extraction/mock_flutter/services.dart
pkgs/intl_translation/test/message_extraction/print_to_list.dart
pkgs/intl_translation/test/message_extraction/verify_messages.dart

Add the PR health workflow to this repo.
---
<details>
Note that many Dart repos have a …

Add PR Health workflow

---

.github/ISSUE_TEMPLATE/intl4x.md
README.md
pkgs/intl4x/CHANGELOG.md
pkgs/intl4x/README.md
pkgs/intl4x/pubspec.yaml

- update the main readme to call out the experimental status
- update the package:intl4x readme to add a std markdown badge
- add an issue template for package:intl4x
Let me know if you'd like me to drop the issue template from this PR (this repo has several customized issue templates).
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package …

update the readmes for this repo

---

pkgs/intl/CHANGELOG.md
pkgs/intl/lib/src/intl/date_format.dart
pkgs/intl/lib/src/intl/date_format_field.dart
pkgs/intl/pubspec.yaml
pkgs/intl/test/number_format_compact_icu_test.dart

Closes #176.
---
<details>
Note that many Dart repos have a weekly cadence for …

Add new `EEEEE` pattern for `DateFormat`

---

.github/workflows/publish.yaml

Due to recent `dart-lang/ecosystem` changes.
---
<details>
Note that many Dart repos …

Write comments on forks

---

pkgs/intl_translation/CHANGELOG.md
pkgs/intl_translation/bin/make_examples_const.dart
pkgs/intl_translation/bin/rewrite_intl_messages.dart
pkgs/intl_translation/lib/src/message_rewriter.dart
pkgs/intl_translation/lib/src/messages/complex_message.dart
pkgs/intl_translation/lib/src/messages/composite_message.dart
pkgs/intl_translation/lib/src/messages/submessages/gender.dart
pkgs/intl_translation/lib/src/messages/submessages/plural.dart
pkgs/intl_translation/lib/src/messages/submessages/select.dart
pkgs/intl_translation/pubspec.yaml
pkgs/intl_translation/test/generate_localized/code_map_test.dart
pkgs/intl_translation/test/message_extraction/examples_parsing_test.dart
pkgs/intl_translation/test/message_extraction/make_hardcoded_translation.dart
pkgs/intl_translation/test/message_extraction/message_extraction_flutter_test.dart
pkgs/intl_translation/test/message_extraction/message_extraction_json_test.dart
pkgs/intl_translation/test/message_extraction/part_of_sample_with_messages.dart
pkgs/intl_translation/test/two_components/component.dart
pkgs/intl_translation/test/two_components/initialize_child_test.dart
pkgs/intl_translation/test/two_components/main_app_test.dart

Fixes #746.
---
<details>
Note that many Dart repos have a weekly cadence for reviewing …

Rev analyzer dep

---

pkgs/intl4x/CHANGELOG.md
pkgs/intl4x/lib/src/plural_rules/plural_rules_4x.dart
pkgs/intl4x/test/plural_rules_test.dart

Missing number formatting options, see #792.
---
<details>
Note that many Dart repos …

Add support for plural rules from ICU4X

---

.github/workflows/intl.yml
pkgs/intl/CHANGELOG.md
pkgs/intl/lib/find_locale.dart
pkgs/intl/lib/intl_browser.dart
pkgs/intl/lib/src/http_request_data_reader.dart
pkgs/intl/lib/src/locale/locale_extensions.dart
pkgs/intl/lib/src/locale/locale_implementation.dart
pkgs/intl/pubspec.yaml
pkgs/intl/test/number_format_compact_web_test.dart

Reland "Support WASM for `package:intl`"

---

pkgs/intl4x/CHANGELOG.md
pkgs/intl4x/hook/build.dart
pkgs/intl4x/pubspec.yaml

Move hook deps from dev_deps to deps.
---
<details>
Note that many Dart …

Fix dependencies in intl4x

---

.github/workflows/intl4x.yml
.github/workflows/intl4x_artifacts.yml
pkgs/intl4x/CHANGELOG.md
pkgs/intl4x/hook/build.dart
pkgs/intl4x/pubspec.yaml

.
---
<details>
Note that many Dart repos have a weekly cadence for …

Release `intl4x: 0.9.2`

---

pkgs/intl/CHANGELOG.md
pkgs/intl/lib/src/intl/constants.dart

Fixes #890
---
<details>
Note that many Dart repos have a weekly cadence …

Update currency symbol for `MKD`

---

pkgs/intl/CHANGELOG.md
pkgs/intl/pubspec.yaml

Fixes #908 
Fixes #793
---
<details>
Note that many Dart repos have a …

Publish `v0.20.0` of `package:intl`

---

README.md

- update the issue tracker links to use a more terse form (this renders better in the markdown table)
---
<details> …

update the issue tracker links

---

.github/workflows/intl4x_artifacts.yml

The hashes.dart file was moved but the path wasn't updated.

[intl4x] Fix path in intl4x_artifacts.yml

---

pkgs/intl4x/CHANGELOG.md
pkgs/intl4x/example/web/main.dart
pkgs/intl4x/lib/src/collation/collation_ecma.dart
pkgs/intl4x/lib/src/datetime_format/datetime_format_ecma.dart
pkgs/intl4x/lib/src/display_names/display_names_ecma.dart
pkgs/intl4x/lib/src/intl_browser.dart
pkgs/intl4x/lib/src/list_format/list_format_ecma.dart
pkgs/intl4x/lib/src/locale/locale.dart
pkgs/intl4x/lib/src/locale/locale_ecma.dart
pkgs/intl4x/lib/src/locale/locale_native.dart
pkgs/intl4x/lib/src/number_format/number_format_ecma.dart
pkgs/intl4x/lib/src/plural_rules/plural_rules_ecma.dart
pkgs/intl4x/pubspec.yaml
pkgs/intl4x/test/ecma/numberformat_test.dart
pkgs/intl4x/test/locale/locale_test.dart

Removes any deps on package:js by using newer patterns.
---
<details>
Note …

Remove `package:js` dependency

---

.github/workflows/intl4x.yml
pkgs/intl4x/CHANGELOG.md
pkgs/intl4x/pubspec.yaml

Publish new version
---
<details>
Note that many Dart repos have a weekly …

Publish `package:intl4x: 0.11.0`

---

pkgs/intl4x/tool/regenerate_hashes.dart

Auto-format now inserts a trailing comma.
---
<details>
Note that many …

Fix hashes.dart formatting

---

pkgs/intl_translation/CHANGELOG.md
pkgs/intl_translation/lib/src/messages/constant_evaluator.dart
pkgs/intl_translation/test/constant_evaluator_test.dart

After this failed some internal tests.
cc @Peetee06 
---
<details>
Note …

Fix constant evaluator
